name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    types: [opened]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: |
            leticiacarelli/somativa2devops:v1
            leticiacarelli/somativa2devops:latest

      - name: Run SAST
        uses: AppThreat/sast-scan-action@master
        with:
          type: "python"

      - name: Upload SAST reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports

  send_notification:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Requests Library
        run: pip install requests

      - name: Send Telegram Notification
        run: |
          python send_telegram_message.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
