name: Security Tests

on:
  push:
    branches: [main]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OWASP ZAP security scan
        run: docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t <http://localhost:3000> -J /zap/wrk/report.json -r "ZAP Baseline Report"
