name: Security Tests

on:
  push:
    branches: [main]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CodeQL
        uses: github/codeql-actions/setup-node@v2
        with:
          languages: javascript

      - name: Analyze code with CodeQL
        uses: github/codeql-actions/analyze@v2
