name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: |
            leticiacarelli/somativa2devops:v1
            leticiacarelli/somativa2devops:latest

      - name: Run SAST
        uses: AppThreat/sast-scan-action@master
        with:
          type: "python"

      - name: Upload SAST reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
