name: Security Tests

on:
  push:
    branches: [main]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CodeQL
        uses: github/codeql-action/setup-node@v2 # Corrigido o caminho para setup-node
        with:
          languages: javascript # Altere para a linguagem do seu projeto

      - name: Analyze code with CodeQL
        uses: github/codeql-action/analyze@v2
