name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: |
            leticiacarelli/somativa2devops:v1
            leticiacarelli/somativa2devops:latest

  DAST:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Install OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz
          tar -xvf ZAP_2.11.0_Linux.tar.gz
          cd ZAP_2.11.0
      - name: Run OWASP ZAP Scan
        run: |
          ./zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config scanner.attackOnStart=true -config connection.dnsTtlSuccessfulQueries=-1 -config connection.dnsTtlFailedQueries=-1 -config script.scriptsByDirectory=/zap/wrk
