snyk:
  stage: test
  image: 
    name: ${IMAGE}
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - apk add curl
    - curl https://static.snyk.io/cli/latest/snyk-linux -o snyk && chmod +x ./snyk
    - ./snyk auth ${SNYK_TOKEN}
    - ./snyk test --json > snyk-results.json
    - if [[ $? -gt 0 ]]; then echo "Application is not secure, check the job artifact to fix these issues."; fi;
  artifacts:
    when: always
    paths:
    - snyk-results.json
  allow_failure: true

snyk-production:
  stage: test
  image: 
    name: ${PROD_IMAGE}
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apk add curl
    - curl https://static.snyk.io/cli/latest/snyk-linux -o snyk && chmod +x ./snyk
    - ./snyk auth ${SNYK_TOKEN}
    - ./snyk test --json > snyk-results.json
    - if [[ $? -gt 0 ]]; then echo "Application is not secure, check the job artifact to fix these issues."; fi;
  artifacts:
    when: always
    paths:
    - snyk-results.json
  allow_failure: true
